play.http.secret.key = "<GENERER_AVEC: openssl rand -hex 32>"

search {
  index = cortex
  uri = "http://elasticsearch:9200"
}

cache.job = 10 minutes

job {
  timeout = 30 minutes
  directory = /tmp/cortex-jobs
}

analyzer {
  urls = [
    "/opt/Cortex-Analyzers/analyzers"
  ]
}
